language: node_js
node_js:
- '6'
before_install:
- openssl aes-256-cbc -K $encrypted_6c6eba60bc7b_key -iv $encrypted_6c6eba60bc7b_iv -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name "ssarcandy"
- git config --global user.email ssarcandy@gmail.com
- npm install apidoc -g
- npm install
- git clone https://github.com/Clothet/Clothet-API-Doc doc
- cd doc
script:
- npm run lint 
- npm run jscs
- apidoc -i ../routes
- git remote set-url origin git@github.com:Clothet/Clothet-API-Doc.git
- git add . && git commit -m 'update'
- git push
branches:
only:
- master